[build-system]
requires = ["scikit-build-core>=0.10", "pybind11>=3.0.2"]
build-backend = "scikit_build_core.build"

[project]
name = "slovorez"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["numpy"]

[project.optional-dependencies]
gpu = ["onnxruntime-gpu>=1.21.0"]
cpu = ["onnxruntime>=1.21.0"]

[tool.scikit-build]
wheel.packages = ["src/slovorez"]
cmake.build-type = "Release"
